POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "What's new with nestJs",
  "postType": "post",
  "slug": "new-wwiwth-nest-js1",
  "status": "draft",
  "content": "This is the content of the sample post.",
  "schema": "{\r\n \"@context\": \"https:V\/schema.org\", \r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "https://example.com/featured-image.jpg",
  "publishedOn": "2025-01-01T12:00:00.000Z",
  //"tags": ["tag1", "tag2", "tag3"],
  "metaOptions": {
        "metaValue": "{ \"sidebarEnabled\": true, \"footActive\": true }"
  },
  "authorId" : 5,
  "tags" : [1]
}