##this file will contain all the post requests for the users

POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName" : "Ramya",
    "lastName" : "Lakhani",
    "email" : "rsamdyssa.lakshssasni.u1@gmail.com",
    "password" : "Hello@1234"
}




POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6InJhbXlhLmxha3NoYW5pLnVAZ21haWwuY29tIiwiaWF0IjoxNzM3NzI2NDczLCJleHAiOjE3Mzc3MzAwNzMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.AKh0BYM-dObQZTgyyHaiYOjbCVuNaJCXBLrVFy_W3eg

{
    "users": [
        {
            "firstName" : "Ramya",
            "lastName" : "Lakwhani",
            "email" : "ramwsya.laksshani.us@gmail.com",
            "password" : "Hello@1234"
        },
        {
            "firstName" : "John",
            "lastName" : "Doe",
            "email" : "johwwn.dosse.u@gmail.com",
            "password" : "Hsi@5678"
        }
    ]
}
