POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJlbWFpbCI6InJhbXlhLmxha3NoYW5pLnVAZ21haWwuY29tIiwiaWF0IjoxNzM3Nzg1MzgwLCJleHAiOjE3Mzc3ODg5ODAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.AUC0RMMwC9N-N1vIw2nE-VVZoV7XAzGU1_S9GQJrwAs

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIyLCJpYXQiOjE3Mzc3ODUzMTIsImV4cCI6MTczNzg3MTcxMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.FgcPBhUGx9pWV6DSXVoPFI3EMnZlZZyDTWjy4DqUcyk"
}